"""Write results/SUMMARY.md: the key numbers, generated from results/tables (never typed by hand)."""

from __future__ import annotations

import numpy as np
import pandas as pd

from asrshift.paths import RESULTS_DIR

SETS = {"eka_test": "Eka test", "pm_turn_test": "PriMock57 turns (test)", "pm_window_test": "PriMock57 windows (test)"}
# see docs/PROTOCOL.md, Amendment 6
VERDICT_NOTES = {"H3b": " (unstable\\*)"}


def _p(x, d=1):
    return "–" if x is None or (isinstance(x, float) and np.isnan(x)) else f"{100 * x:.{d}f}%"


def _ci(r, k, d=1):
    lo, hi = r.get(f"{k}_lo"), r.get(f"{k}_hi")
    if lo is None or pd.isna(lo):
        return _p(r[k], d)
    return f"{_p(r[k], d)} [{_p(lo, d)}, {_p(hi, d)}]"


def _f(x, d=3):
    return "–" if x is None or pd.isna(x) else f"{x:.{d}f}"


def _table(rows: list[list], head: list[str]) -> str:
    out = ["| " + " | ".join(head) + " |", "|" + "|".join("---" if i == 0 else "---:" for i in range(len(head))) + "|"]
    out += ["| " + " | ".join(str(c).replace("|", "\\|") for c in r) + " |" for r in rows]
    return "\n".join(out)


def build(model: str = "small") -> str:
    t = RESULTS_DIR / "tables" / model.replace("/", "_")
    e = t / "err"
    asr = pd.read_csv(t / "asr_summary.csv").set_index("set")
    cal = pd.read_csv(e / "calibration.csv")
    ops = pd.read_csv(e / "operating_points.csv")
    hyp = pd.read_csv(e / "hypotheses.csv")
    s = [f"# Results summary (whisper-{model})", "",
         "Generated by `asrshift report` from `results/tables/`. Intervals are 95% cluster-bootstrap "
         "intervals (speakers/sessions for Eka, consultations for PriMock57). Label: transcript WER > 10% "
         "after normalisation. See docs/PROTOCOL.md for every definition.", ""]

    s += ["## ASR quality", ""]
    rows = []
    for k, name in SETS.items():
        r = asr.loc[k]
        rows.append([name, f"{int(r['units']):,}", f"{r['hours']:.2f}", _ci(r, "wer"), _ci(r, "err_rate"),
                     _ci(r, "crit_err_rate"), _p(r["number_acc"]), _p(r["negation_acc"]),
                     _p(r.get("entity_acc")) if k == "eka_test" else "–",
                     f"{_ci(r, 'term_acc')} (n={int(r['n_terms'])})" if "term_acc" in r and pd.notna(r.get("term_acc")) else "–"])
    s += [_table(rows, ["Set", "Units", "Hours", "WER", "WER > 10%", "Dose/negation error", "Numbers right",
                        "Negations right", "Eka entities right", "Shared medical terms right"]), ""]

    s += ["## Confirmatory hypotheses (Holm-adjusted, one-sided)", ""]
    notes = VERDICT_NOTES if model.replace("/", "_") == "small" else {}  # amendment 6 concerns whisper-small
    if model.replace("/", "_") != "small":
        s += ["*Exploratory model (protocol amendment 5): the tests are run as for whisper-small, but they "
              "are not part of the confirmatory family.*", ""]
    rows = [[r["hypothesis"], r["statement"], _f(r["estimate"]), f"[{_f(r['ci_lo'])}, {_f(r['ci_hi'])}]",
             _f(r["p_holm"], 4) if r["testable"] else "not testable",
             ("**supported**" if r["supported"] else "not supported") + notes.get(r["hypothesis"], "")]
            for _, r in hyp.iterrows()]
    s += [_table(rows, ["", "Statement", "Estimate", "95% CI", "p (Holm)", "Verdict"]), ""]
    if any(h in set(hyp["hypothesis"]) for h in notes):
        s += ["\\* H3b's verdict flips with the post-hoc scoring correction of Amendment 6 (p = 0.20 before, "
              "0.006 after), so it is reported as unstable and not counted as a confirmatory finding.", ""]

    nb = e / "null_baseline.csv"
    if nb.exists():
        n = pd.read_csv(nb)
        h = hyp.set_index("hypothesis")
        s += ["### Against the null baseline (word probabilities perfectly calibrated by construction)", ""]
        rows = []
        for col, hname, label in (("citl_windows", "H1", "P3 calibration-in-the-large on windows"),
                                  ("miss_windows_minus_eka", "H2", "extra share of errors auto-accepted, windows − Eka")):
            q = n[col].quantile([0.025, 0.5, 0.975])
            rows.append([label, _f(h.loc[hname, "estimate"]), f"{_f(q[0.5])} [{_f(q[0.025])}, {_f(q[0.975])}]"])
        s += [_table(rows, ["Statistic", "Observed", "Null median [2.5%, 97.5%]"]), ""]

    s += ["## Calibration of P(transcript WER > 10%)", ""]
    rows = []
    for _, r in cal[cal["policy"].isin(["P3", "P3-conf", "P4", "P4-refit", "ceiling"])].iterrows():
        rows.append([SETS.get(r["eval"], r["eval"]), r["policy"], _p(r["base_rate"]), _p(r["mean_p"]),
                     f"{_f(r['ece'])} [{_f(r.get('ece_lo'))}, {_f(r.get('ece_hi'))}]", _f(r["citl"])])
    s += [_table(rows, ["Set", "Policy", "Observed error rate", "Mean predicted", "ECE", "Predicted − observed"]), ""]

    s += ["## Review budget of 10% (thresholds set on the tuning set, then frozen)", ""]
    rows = []
    for _, r in ops[(ops["point"] == "budget_0.10") & ops["policy"].isin(["P1", "P2", "P3", "P3-conf", "P1-retuned", "P4"])].iterrows():
        rows.append([SETS[r["eval"]], r["policy"], _ci(r, "review_rate"), _ci(r, "err_caught"), _ci(r, "accepted_err_rate"),
                     _p(r.get("accepted_crit_err_rate"))])
    s += [_table(rows, ["Set", "Policy", "Sent to review", "Erroneous caught", "Accepted & erroneous",
                        "Accepted with dose/negation error"]), ""]

    s += ["## Risk target: accepted error ≤ 20%", ""]
    rows = []
    sel = ops[ops["point"].isin(["risk_0.20", "riskcp_0.20", "plugin_0.20"]) & ops["policy"].isin(["P1", "P3", "P1-retuned", "P4"])]
    for _, r in sel.iterrows():
        rows.append([SETS[r["eval"]], r["policy"], r["point"].split("_")[0], "yes" if r["feasible"] else "no (review all)",
                     _ci(r, "review_rate"), _ci(r, "accepted_err_rate")])
    s += [_table(rows, ["Set", "Policy", "Rule", "Feasible", "Sent to review", "Accepted & erroneous"]), ""]

    for name, title in (("deployment", "Per consultation (PriMock57 test windows)"), ("drift_alarm", "Label-free drift alarm"),
                        ("length_strata", "Length strata (P3)"), ("sensitivity", "Sensitivity analyses (windows)"),
                        ("devpool_robustness", "Source thresholds tuned on calibration + validation")):
        p = e / f"{name}.csv"
        if p.exists():
            d = pd.read_csv(p)
            rows = [[_f(v) if isinstance(v, float) else v for v in r] for r in d.itertuples(index=False)]
            s += [f"## {title}", "", _table(rows, list(d.columns)), ""]
    return "\n".join(s)


def run(cfg: dict | None = None, model: str | None = None) -> None:
    model = model or (cfg or {}).get("asr", {}).get("model") or "small"
    tag = model.replace("/", "_")
    out = RESULTS_DIR / ("SUMMARY.md" if tag == "small" else f"SUMMARY_{tag}.md")
    out.write_text(build(model), encoding="utf-8")
    print(f"wrote {out}")
